---
jobs:
- name: run-cloudformation
  plan:
  - get: pipeline
  - get: cloudformation
    resource: elastic-runtime
    params:
      globs: [ "*cloudformation.json" ]
  - task: cloudformation
    file: pipeline/tasks/cloudformation.yml
    params:
      AWS_ACCESS_KEY_ID: {{aws-access-key-id}}
      AWS_SECRET_ACCESS_KEY: {{aws-secret-access-key}}
      AWS_DEFAULT_REGION: {{aws-default-region}}
      AWS_SSL_CERTIFICATE_ARN: {{aws-ssl-certificate-arn}}

resources:
- name: pipeline
  type: git
  source:
    uri: {{git-uri}}
    branch: {{git-branch}}

- name: elastic-runtime
  type: pivnet
  source:
    api_token: {{pivnet-api-token}}
    product_slug: elastic-runtime
    product_version: {{elstic-runtime-version}}

resource_types:
- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final
