---
aws-params: &aws-params
  AWS_ACCESS_KEY_ID: {{aws-access-key-id}}
  AWS_SECRET_ACCESS_KEY: {{aws-secret-access-key}}
  AWS_DEFAULT_REGION: {{aws-region}}
  AWS_CLOUDFORMATION_STACK_NAME: {{aws-cloudformation-stack-name}}

groups:
- name: deploy
  jobs:
  - create-stack
  - launch-opsman
  - configure-opsman
  - install-elastic-runtime
- name: destroy
  jobs:
  - delete-rds
  - delete-stack
  - terminate-opsman

jobs:
- name: create-stack
  plan:
  - get: pipeline
  - get: cloudformation
    resource: elastic-runtime
    params:
      globs: [ "*cloudformation.json" ]
  - task: create-stack
    file: pipeline/tasks/create-stack.yml
    params:
      <<: *aws-params
      AWS_KEY_NAME: {{aws-key-name}}
      AWS_SSL_CERTIFICATE_ARN: {{aws-ssl-certificate-arn}}
      RDS_DBNAME: {{rds-dbname}}
      RDS_USERNAME: {{rds-username}}
      RDS_PASSWORD: {{rds-password}}

- name: launch-opsman
  plan:
  - get: pipeline
    trigger: true
    passed: [create-stack]
  - task: launch-opsman
    file: pipeline/tasks/launch-opsman.yml
    params:
      <<: *aws-params
      AWS_KEY_NAME: {{aws-key-name}}
      AWS_HOSTED_ZONE_ID: {{aws-hosted-zone-id}}
      OPS_MANAGER_AMI: {{ops-manager-ami}}
      OPS_MANAGER_DOMAIN: {{ops-manager-domain}}
      OPS_MANAGER_ADMIN_USER: {{ops-manager-admin-user}}
      OPS_MANAGER_ADMIN_PASS: {{ops-manager-admin-pass}}
      OPS_MANAGER_DECRYPT_PASSPHRASE: {{ops-manager-decrypt-passphrase}}

- name: configure-opsman
  plan:
  - get: pipeline
    trigger: true
    passed: [launch-opsman]
  - task: configure-opsman
    file: pipeline/tasks/configure-opsman.yml
    params:
      <<: *aws-params
      AWS_KEY_NAME: {{aws-key-name}}
      AWS_SSH_PRIVATE_KEY: {{aws-ssh-private-key}}
      OPS_MANAGER_DOMAIN: {{ops-manager-domain}}
      OPS_MANAGER_ADMIN_USER: {{ops-manager-admin-user}}
      OPS_MANAGER_ADMIN_PASS: {{ops-manager-admin-pass}}
      NTP_SERVERS: {{ntp-servers}}
      S3_ENDPOINT: {{aws-s3-endpoint}}

- name: install-elastic-runtime
  plan:
  - aggregate:
    - get: pipeline
    - get: elastic-runtime
      params:
        globs: [ "cf-*.pivotal" ]
    - get: stemcell
      params:
        globs: [ "light-bosh-stemcell-*-aws-xen-hvm-ubuntu-trusty-go_agent.tgz" ]
  - task: install-elastic-runtime
    file: pipeline/tasks/install-elastic-runtime.yml
    params:
      <<: *aws-params
      OPS_MANAGER_DOMAIN: {{ops-manager-domain}}
      OPS_MANAGER_ADMIN_USER: {{ops-manager-admin-user}}
      OPS_MANAGER_ADMIN_PASS: {{ops-manager-admin-pass}}
      AWS_HOSTED_ZONE_ID: {{aws-hosted-zone-id}}
      CF_SYSTEM_DOMAIN: {{cf-system-domain}}
      CF_APPS_DOMAIN: {{cf-apps-domain}}
      CF_NOTIFY_EMAIL: {{cf-notify-email}}
      CF_SMTP_FROM: {{cf-smtp-from}}
      CF_SMTP_ADDRESS: {{cf-smtp-address}}
      CF_SMTP_PORT: {{cf-smtp-port}}
      CF_SMTP_USERNAME: {{cf-smtp-username}}
      CF_SMTP_PASSWORD: {{cf-smtp-password}}
      CF_S3_ENDPOINT: {{cf-s3-endpoint}}

- name: delete-rds
  plan:
  - get: pipeline
  - task: delete-rds
    file: pipeline/tasks/delete-rds.yml
    params:
      <<: *aws-params

- name: delete-stack
  plan:
  - get: pipeline
  - task: delete-stack
    file: pipeline/tasks/delete-stack.yml
    params:
      <<: *aws-params
      AWS_HOSTED_ZONE_ID:
      OPS_MANAGER_DOMAIN:

- name: terminate-opsman
  plan:
  - get: pipeline
  - task: terminate-opsman
    file: pipeline/tasks/terminate-opsman.yml
    params:
      <<: *aws-params
      AWS_HOSTED_ZONE_ID: {{aws-hosted-zone-id}}
      OPS_MANAGER_DOMAIN: {{ops-manager-domain}}

resources:
- name: pipeline
  type: git
  source:
    uri: {{git-uri}}
    branch: {{git-branch}}

- name: elastic-runtime
  type: pivnet
  source:
    api_token: {{pivnet-api-token}}
    product_slug: elastic-runtime
    product_version: {{elstic-runtime-version}}

- name: stemcell
  type: pivnet
  source:
    api_token: {{pivnet-api-token}}
    product_slug: stemcells
    product_version: {{elstic-runtime-stemcell-version}}

resource_types:
- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final
