---

aws-params: &aws-params
  AWS_ACCESS_KEY_ID: {{aws-access-key-id}}
  AWS_SECRET_ACCESS_KEY: {{aws-secret-access-key}}
  AWS_DEFAULT_REGION: {{aws-default-region}}
  AWS_CLOUDFORMATION_STACK_NAME: {{aws-cloudformation-stack-name}}

jobs:
- name: create-stack
  plan:
  - get: pipeline
  - get: cloudformation
    resource: elastic-runtime
    params:
      globs: [ "*cloudformation.json" ]
  - task: create-stack
    file: pipeline/tasks/create-stack.yml
    params:
      <<: *aws-params
      AWS_KEY_NAME: {{aws-key-name}}
      AWS_SSL_CERTIFICATE_ARN: {{aws-ssl-certificate-arn}}

- name: delete-rds
  plan:
  - get: pipeline
  - task: delete-rds
    file: pipeline/tasks/delete-rds.yml
    params:
      <<: *aws-params

- name: delete-stack
  plan:
  - get: pipeline
  - task: delete-stack
    file: pipeline/tasks/delete-stack.yml
    params:
      <<: *aws-params

- name: deploy-opsman
  plan:
  - get: pipeline
  - task: deploy-opsman
    file: pipeline/tasks/deploy-opsman.yml
    params:
      <<: *aws-params
      AWS_KEY_NAME: {{aws-key-name}}
      AWS_HOSTED_ZONE_ID: {{aws-hosted-zone-id}}
      OPS_MANAGER_AMI: {{ops-manager-ami}}
      OPS_MANAGER_DOMAIN: {{ops-manager-domain}}

resources:
- name: pipeline
  type: git
  source:
    uri: {{git-uri}}
    branch: {{git-branch}}

- name: elastic-runtime
  type: pivnet
  source:
    api_token: {{pivnet-api-token}}
    product_slug: elastic-runtime
    product_version: {{elstic-runtime-version}}

resource_types:
- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final
