---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: patrickcrocker/aws-cli
    tag: 'latest'

params:
  AWS_ACCESS_KEY_ID:
  AWS_SECRET_ACCESS_KEY:
  AWS_DEFAULT_REGION:

inputs:
- name: pipeline
- name: cloudformation

run:
  path: pipeline/tasks/cloudformation.sh
