---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: patrickcrocker/aws-cli
    tag: 'latest'

params:
  AWS_ACCESS_KEY_ID:
  AWS_SECRET_ACCESS_KEY:
  AWS_DEFAULT_REGION:
  AWS_KEY_NAME:
  OPS_MANAGER_AMI:

inputs:
- name: pipeline

run:
  path: pipeline/tasks/deploy-opsman.sh
