---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: patrickcrocker/lotc
    tag: '1.0.1-rc.2'

params:
  AWS_ACCESS_KEY_ID:
  AWS_SECRET_ACCESS_KEY:
  AWS_DEFAULT_REGION:
  AWS_KEY_NAME:
  AWS_HOSTED_ZONE_ID:
  OPS_MANAGER_AMI:
  OPS_MANAGER_DOMAIN:
  OPS_MANAGER_ADMIN_USER:
  OPS_MANAGER_ADMIN_PASS:
  OPS_MANAGER_DECRYPT_PASSPHRASE:

inputs:
- name: pipeline

run:
  path: pipeline/tasks/launch-opsman.sh
