---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: patrickcrocker/lotc
    tag: '1.0.1-rc.2'

params:
  OPS_MANAGER_DOMAIN:
  OPS_MANAGER_ADMIN_USER:
  OPS_MANAGER_ADMIN_PASS:
  AWS_SSH_PRIVATE_KEY:

inputs:
- name: pipeline

run:
  path: pipeline/tasks/stop-pcf.sh
