---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: patrickcrocker/lotc
    tag: '1.0.1-rc.2'

params:
  AWS_ACCESS_KEY_ID:
  AWS_SECRET_ACCESS_KEY:
  AWS_DEFAULT_REGION:
  AWS_HOSTED_ZONE_ID:
  OPS_MANAGER_DOMAIN:

inputs:
- name: pipeline

run:
  path: pipeline/tasks/terminate-opsman.sh
